import { beforeEach, describe, expect, it, vi } from 'vitest'

const { mockExecFile, mockExecFileCustom } = vi.hoisted(() => {
  const mockExecFileCustom = vi.fn()
  const mockExecFile: any = vi.fn()
  mockExecFile[Symbol.for('nodejs.util.promisify.custom')] = mockExecFileCustom
  return { mockExecFile, mockExecFileCustom }
})

vi.mock('node:child_process', () => ({
  execFileSync: vi.fn(),
  execFile: mockExecFile,
}))

vi.mock('node:fs', () => ({
  existsSync: vi.fn(),
  rmSync: vi.fn(),
}))

import { execFileSync } from 'node:child_process'
import * as fs from 'node:fs'
import {
  _resetGhCliCache,
  approvePR,
  checkGhCliAvailable,
  generatePrBranchName,
  mergeBranchAndPushPR,
  mergePR,
} from '@main/git/git-github-pr'

function setupExecFileAsyncMock(
  handler: (cmd: string, args: readonly string[]) => { stdout?: string; stderr?: string; error?: Error | null },
) {
  mockExecFileCustom.mockImplementation((cmd: string, cmdArgs?: readonly string[]) => {
    const args = cmdArgs || []
    const result = handler(cmd, args)
    if (result.error) {
      return Promise.reject(result.error)
    }
    return Promise.resolve({ stdout: result.stdout || '', stderr: result.stderr || '' })
  })
}

function setupSyncHelpers() {
  vi.mocked(execFileSync).mockImplementation((cmd: string, args?: readonly string[]) => {
    const command = `${cmd} ${(args || []).join(' ')}`
    if (command.startsWith('git check-ref-format --branch')) return Buffer.from('')
    if (command === 'git symbolic-ref refs/remotes/origin/HEAD') throw new Error('no origin head')
    if (command === 'git rev-parse --verify main') return Buffer.from('abc123')
    if (command === 'git rev-parse --verify origin/main') return Buffer.from('def456')
    throw new Error(`Unexpected command: ${command}`)
  })
}

describe('git-github-pr', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    vi.mocked(fs.existsSync).mockReturnValue(true)
    _resetGhCliCache()
  })

  it('checkGhCliAvailable should cache the gh --version result until _resetGhCliCache is called', async () => {
    let callCount = 0
    setupExecFileAsyncMock((cmd, args) => {
      if (cmd === 'gh' && args[0] === '--version') {
        callCount += 1
        return { stdout: 'gh version 2.0.0' }
      }
      return { error: new Error(`Unexpected command: ${cmd} ${args.join(' ')}`) }
    })

    await expect(checkGhCliAvailable()).resolves.toBe(true)
    await expect(checkGhCliAvailable()).resolves.toBe(true)
    expect(callCount).toBe(1)

    _resetGhCliCache()
    await expect(checkGhCliAvailable()).resolves.toBe(true)
    expect(callCount).toBe(2)
  })

  it('generatePrBranchName should derive a yolium/<slug> branch name from autogenerated worktree branches and preserve user-defined branches', () => {
    expect(generatePrBranchName('yolium-1738900000000-abc123', 'Add auth flow')).toBe(
      'yolium/add-auth-flow',
    )
    expect(generatePrBranchName('feature/custom-branch', 'Ignored title')).toBe(
      'feature/custom-branch',
    )
  })

  it('mergeBranchAndPushPR should return a failure when temporary PR branch creation fails', async () => {
    setupSyncHelpers()
    setupExecFileAsyncMock((cmd, args) => {
      const command = `${cmd} ${args.join(' ')}`
      if (command === 'git fetch origin') return {}
      if (command === 'git branch -D yolium/add-auth') return {}
      if (command === 'git branch yolium/add-auth origin/main') {
        const error = new Error('branch failed') as Error & { stderr: string }
        error.stderr = 'fatal: not a valid object name'
        return { error }
      }
      return { error: new Error(`Unexpected command: ${command}`) }
    })

    await expect(
      mergeBranchAndPushPR('/project', 'yolium-123-abc', '/worktree', 'Add auth', 'Description'),
    ).resolves.toEqual({
      success: false,
      error: 'Failed to create PR branch: fatal: not a valid object name',
    })
  })

  it('mergeBranchAndPushPR should return a conflict result and clean up temp artifacts when squash merge reports conflicts', async () => {
    setupSyncHelpers()
    const calls: string[] = []
    setupExecFileAsyncMock((cmd, args) => {
      const command = `${cmd} ${args.join(' ')}`
      calls.push(command)
      if (command === 'git fetch origin') return {}
      if (command === 'git branch -D yolium/add-auth') return {}
      if (command === 'git branch yolium/add-auth origin/main') return {}
      if (command.startsWith('git worktree add ')) return {}
      if (command === 'git merge --squash yolium-123-abc') {
        const error = new Error('merge failed') as Error & { stderr: string }
        error.stderr = 'Automatic merge failed\nCONFLICT (content): Merge conflict in src/app.ts'
        return { error }
      }
      if (command === 'git merge --abort') return {}
      if (command.startsWith('git worktree remove ')) return {}
      return {}
    })

    await expect(
      mergeBranchAndPushPR('/project', 'yolium-123-abc', '/agent-worktree', 'Add auth', 'Description'),
    ).resolves.toEqual({
      success: false,
      conflict: true,
      error: 'Merge conflicts detected. Please resolve manually.',
    })
    expect(calls.some((call) => call.startsWith('git worktree remove '))).toBe(true)
    expect(calls).toContain('git branch -D yolium/add-auth')
  })

  it('mergeBranchAndPushPR should return a push failure when git push rejects the PR branch', async () => {
    setupSyncHelpers()
    setupExecFileAsyncMock((cmd, args) => {
      const command = `${cmd} ${args.join(' ')}`
      if (command === 'git fetch origin') return {}
      if (command === 'git branch -D yolium/add-auth') return {}
      if (command === 'git branch yolium/add-auth origin/main') return {}
      if (command.startsWith('git worktree add ')) return {}
      if (command === 'git merge --squash yolium-123-abc') return {}
      if (command.startsWith('git commit -m ')) return {}
      if (command === 'git push -u origin yolium/add-auth') {
        const error = new Error('push failed') as Error & { stderr: string }
        error.stderr = 'remote: Permission denied'
        return { error }
      }
      if (command.startsWith('git worktree remove ')) return {}
      if (command === 'git branch -D yolium/add-auth') return {}
      return {}
    })

    await expect(
      mergeBranchAndPushPR('/project', 'yolium-123-abc', '/agent-worktree', 'Add auth', 'Description'),
    ).resolves.toEqual({
      success: false,
      error: 'Failed to push branch: remote: Permission denied',
    })
  })

  it('mergeBranchAndPushPR should return partial success with prBranch when gh is unavailable after a successful push', async () => {
    setupSyncHelpers()
    setupExecFileAsyncMock((cmd, args) => {
      const command = `${cmd} ${args.join(' ')}`
      if (command === 'git fetch origin') return {}
      if (command === 'git branch -D yolium/add-auth') return {}
      if (command === 'git branch yolium/add-auth origin/main') return {}
      if (command.startsWith('git worktree add ')) return {}
      if (command === 'git merge --squash yolium-123-abc') return {}
      if (command.startsWith('git commit -m ')) return {}
      if (command === 'git push -u origin yolium/add-auth') return {}
      if (cmd === 'gh' && args[0] === '--version') {
        return { error: new Error('spawn gh ENOENT') }
      }
      if (command.startsWith('git worktree remove ')) return {}
      return {}
    })

    await expect(
      mergeBranchAndPushPR('/project', 'yolium-123-abc', '/agent-worktree', 'Add auth', 'Description'),
    ).resolves.toEqual({
      success: true,
      prBranch: 'yolium/add-auth',
      error: 'GitHub CLI (gh) is not installed. Install it from https://cli.github.com to create PRs automatically. Branch was pushed — create the PR manually.',
    })
  })

  it('mergeBranchAndPushPR should return success with prUrl and prBranch on the fully successful path', async () => {
    setupSyncHelpers()
    setupExecFileAsyncMock((cmd, args) => {
      const command = `${cmd} ${args.join(' ')}`
      if (command === 'git fetch origin') return {}
      if (command === 'git branch -D yolium/add-auth') return {}
      if (command === 'git branch yolium/add-auth origin/main') return {}
      if (command.startsWith('git worktree add ')) return {}
      if (command === 'git merge --squash yolium-123-abc') return {}
      if (command.startsWith('git commit -m ')) return {}
      if (command === 'git push -u origin yolium/add-auth') return {}
      if (cmd === 'gh' && args[0] === '--version') return { stdout: 'gh version 2.0.0' }
      if (cmd === 'gh' && args[0] === 'pr') {
        return { stdout: 'https://github.com/yolium/repo/pull/42\n' }
      }
      if (command.startsWith('git worktree remove ')) return {}
      if (command === 'git branch -d yolium-123-abc') return {}
      return {}
    })

    await expect(
      mergeBranchAndPushPR('/project', 'yolium-123-abc', '/agent-worktree', 'Add auth', 'Description'),
    ).resolves.toEqual({
      success: true,
      prUrl: 'https://github.com/yolium/repo/pull/42',
      prBranch: 'yolium/add-auth',
    })
  })

  it('mergeBranchAndPushPR should preserve user-defined branch names on the successful path', async () => {
    setupSyncHelpers()
    setupExecFileAsyncMock((cmd, args) => {
      const command = `${cmd} ${args.join(' ')}`
      if (command === 'git fetch origin') return {}
      if (command === 'git branch -D feature/custom-branch') return {}
      if (command === 'git branch feature/custom-branch origin/main') return {}
      if (command.startsWith('git worktree add ')) return {}
      if (command === 'git merge --squash feature/custom-branch') return {}
      if (command.startsWith('git commit -m ')) return {}
      if (command === 'git push -u origin feature/custom-branch') return {}
      if (cmd === 'gh' && args[0] === '--version') return { stdout: 'gh version 2.0.0' }
      if (cmd === 'gh' && args[0] === 'pr') return { stdout: 'https://github.com/yolium/repo/pull/43\n' }
      if (command.startsWith('git worktree remove ')) return {}
      if (command === 'git branch -d feature/custom-branch') return {}
      return {}
    })

    await expect(
      mergeBranchAndPushPR('/project', 'feature/custom-branch', '/agent-worktree', 'Ignored title', 'Description'),
    ).resolves.toEqual({
      success: true,
      prUrl: 'https://github.com/yolium/repo/pull/43',
      prBranch: 'feature/custom-branch',
    })
  })

  it('mergeBranchAndPushPR should use only the item title as the squash merge commit message', async () => {
    setupSyncHelpers()
    let capturedCommitMessage: string | undefined
    setupExecFileAsyncMock((cmd, args) => {
      const command = `${cmd} ${args.join(' ')}`
      if (command === 'git fetch origin') return {}
      if (command === 'git branch -D yolium/add-auth') return {}
      if (command === 'git branch yolium/add-auth origin/main') return {}
      if (command.startsWith('git worktree add ')) return {}
      if (command === 'git merge --squash yolium-123-abc') return {}
      if (cmd === 'git' && args[0] === 'commit' && args[1] === '-m') {
        capturedCommitMessage = args[2]
        return {}
      }
      if (command === 'git push -u origin yolium/add-auth') return {}
      if (cmd === 'gh' && args[0] === '--version') return { stdout: 'gh version 2.0.0' }
      if (cmd === 'gh' && args[0] === 'pr') return { stdout: 'https://github.com/yolium/repo/pull/42\n' }
      if (command.startsWith('git worktree remove ')) return {}
      if (command === 'git branch -d yolium-123-abc') return {}
      return {}
    })

    await mergeBranchAndPushPR('/project', 'yolium-123-abc', '/agent-worktree', 'Add auth', 'Description')

    expect(capturedCommitMessage).toBe('Add auth')
    expect(capturedCommitMessage).not.toContain('yolium-')
    expect(capturedCommitMessage).not.toContain('Squash merge branch')
  })

  it('approvePR should return an install message when gh is not available', async () => {
    setupExecFileAsyncMock((cmd, args) => {
      if (cmd === 'gh' && args[0] === '--version') {
        return { error: new Error('spawn gh ENOENT') }
      }
      return { error: new Error(`Unexpected command: ${cmd} ${args.join(' ')}`) }
    })

    await expect(approvePR('/project', 'https://github.com/owner/repo/pull/1')).resolves.toEqual({
      success: false,
      error: 'GitHub CLI (gh) is not installed. Install it from https://cli.github.com to approve PRs.',
    })
  })

  it('approvePR should approve a PR successfully with the expected gh arguments', async () => {
    let capturedArgs: readonly string[] = []
    setupExecFileAsyncMock((cmd, args) => {
      if (cmd === 'gh' && args[0] === '--version') {
        return { stdout: 'gh version 2.0.0' }
      }
      if (cmd === 'gh' && args[0] === 'pr' && args[1] === 'review') {
        capturedArgs = args
        return {}
      }
      return { error: new Error(`Unexpected command: ${cmd} ${args.join(' ')}`) }
    })

    await expect(approvePR('/project', 'https://github.com/owner/repo/pull/1')).resolves.toEqual({
      success: true,
    })
    expect(capturedArgs).toEqual(['pr', 'review', 'https://github.com/owner/repo/pull/1', '--approve'])
  })

  it('approvePR should fall back to the error message when stderr is unavailable', async () => {
    setupExecFileAsyncMock((cmd, args) => {
      if (cmd === 'gh' && args[0] === '--version') {
        return { stdout: 'gh version 2.0.0' }
      }
      if (cmd === 'gh' && args[0] === 'pr' && args[1] === 'review') {
        return { error: new Error('some error without stderr') }
      }
      return { error: new Error(`Unexpected command: ${cmd} ${args.join(' ')}`) }
    })

    await expect(approvePR('/project', 'https://github.com/owner/repo/pull/1')).resolves.toEqual({
      success: false,
      error: 'Failed to approve PR: some error without stderr',
    })
  })

  it('mergePR should return an install message when gh is not available', async () => {
    setupExecFileAsyncMock((cmd, args) => {
      if (cmd === 'gh' && args[0] === '--version') {
        return { error: new Error('spawn gh ENOENT') }
      }
      return { error: new Error(`Unexpected command: ${cmd} ${args.join(' ')}`) }
    })

    await expect(mergePR('/project', 'https://github.com/owner/repo/pull/1')).resolves.toEqual({
      success: false,
      error: 'GitHub CLI (gh) is not installed. Install it from https://cli.github.com to merge PRs.',
    })
  })

  it('mergePR should return success when gh pr merge succeeds', async () => {
    setupExecFileAsyncMock((cmd, args) => {
      if (cmd === 'gh' && args[0] === '--version') {
        return { stdout: 'gh version 2.0.0' }
      }
      if (cmd === 'gh' && args[0] === 'pr' && args[1] === 'merge') {
        return {}
      }
      return { error: new Error(`Unexpected command: ${cmd} ${args.join(' ')}`) }
    })

    await expect(mergePR('/project', 'https://github.com/owner/repo/pull/1')).resolves.toEqual({
      success: true,
    })
  })

  it('mergePR should invoke gh pr merge --squash --delete-branch and surface stderr on failure', async () => {
    let capturedArgs: readonly string[] = []
    setupExecFileAsyncMock((cmd, args) => {
      if (cmd === 'gh' && args[0] === '--version') {
        return { stdout: 'gh version 2.0.0' }
      }
      if (cmd === 'gh' && args[0] === 'pr' && args[1] === 'merge') {
        capturedArgs = args
        const error = new Error('gh merge failed') as Error & { stderr: string }
        error.stderr = 'merge conflict'
        return { error }
      }
      return { error: new Error(`Unexpected command: ${cmd} ${args.join(' ')}`) }
    })

    await expect(mergePR('/project', 'https://github.com/owner/repo/pull/1')).resolves.toEqual({
      success: false,
      error: 'Failed to merge PR: merge conflict',
    })
    expect(capturedArgs).toEqual([
      'pr',
      'merge',
      'https://github.com/owner/repo/pull/1',
      '--squash',
      '--delete-branch',
    ])
  })

  it('mergePR should run gh in the provided working directory', async () => {
    let capturedCwd: string | undefined
    mockExecFileCustom.mockImplementation((cmd: string, cmdArgs?: readonly string[], options?: { cwd?: string }) => {
      if (cmd === 'gh' && cmdArgs?.[0] === '--version') {
        return Promise.resolve({ stdout: 'gh version 2.0.0', stderr: '' })
      }
      if (cmd === 'gh' && cmdArgs?.[0] === 'pr' && cmdArgs?.[1] === 'merge') {
        capturedCwd = options?.cwd
        return Promise.resolve({ stdout: '', stderr: '' })
      }
      return Promise.reject(new Error(`Unexpected command: ${cmd} ${(cmdArgs || []).join(' ')}`))
    })

    await expect(mergePR('/custom/project/path', 'https://github.com/owner/repo/pull/1')).resolves.toEqual({
      success: true,
    })
    expect(capturedCwd).toBe('/custom/project/path')
  })

  it('mergePR should fall back to Unknown error when stderr and message are empty', async () => {
    setupExecFileAsyncMock((cmd, args) => {
      if (cmd === 'gh' && args[0] === '--version') {
        return { stdout: 'gh version 2.0.0' }
      }
      if (cmd === 'gh' && args[0] === 'pr' && args[1] === 'merge') {
        const error = new Error('') as Error & { stderr?: string }
        error.stderr = ''
        return { error }
      }
      return { error: new Error(`Unexpected command: ${cmd} ${args.join(' ')}`) }
    })

    await expect(mergePR('/project', 'https://github.com/owner/repo/pull/1')).resolves.toEqual({
      success: false,
      error: 'Failed to merge PR: Unknown error',
    })
  })
})
